### ISSUE TITLE
关于shortLabel和longLabel

### ISSUE THREAD

**Issue by Wzhixiang** [leiyun1993/ShortcutsDemo#1]
优先显示longlabel中内容，前提是显示的空间足够放下longlabel中的内容

**Comment by leiyun-studio** [comment]
嗯 谢谢你的解答， 静态创建的时候是这样的，但是动态创建的时候.setShortLabel("Activity") .setLongLabel("Activity_Long")却是反过来优先展示short，是这个我不能理解！
